# Host to use for canonical URL generation (without trailing slash)
host: docs.report-a-death.dev.account.gov.uk

# Header-related options
show_govuk_logo: true
service_name: Report a Death
service_link: https://report-a-death.dev.account.gov.uk
phase: Beta

# Links to show on right-hand-side of header
header_links:
  GitHub: https://github.com/alphagov/di-report-a-death
  Prototypes: https://github.com/alphagov/di-rad-prototypes
  Prototype repo: https://github.com/alphagov/di-rad-prototypes
  Techdocs repo: https://github.com/alphagov/di-report-a-death-techdocs

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: false

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 2

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: true
github_repo: alphagov/di-report-a-death-techdocs
github_branch: main
